image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt --target Lib"

version: '0.0.1+{build}'

build_script:
  - ps: Compress-Archive -Path app.py -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path start_server.bat -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path LICENSE -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path injects -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path static -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path storage -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path templates -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.6.5/python-3.6.5-embed-win32.zip" -OutFile python36.zip
  - ps: Expand-Archive -Path python36.zip -DestinationPath python36
  - ps: Compress-Archive -Path python36 -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"
  - ps: Compress-Archive -Path Lib\* -Update -DestinationPath "allin-injectplot-${Env:APPVEYOR_BUILD_VERSION}.zip"

artifacts:
  - path: 'allin-injectplot-%APPVEYOR_BUILD_VERSION%.zip'

deploy:
  - provider: GitHub
    artifact: 'allin-injectplot-%APPVEYOR_BUILD_VERSION%.zip'
    auth_token:
      secure: zlT9Lhys07Vl1jwbCrvHJdCkcmPZIUcAA750FhzJNt9qbuGldDzn4svOEH20GPnZ
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only
